name = "pastebin-worker"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "copy.8void.sbs"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "ca388691b8d940b9a004038ed2c2e2a1"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://copy.8void.sbs"

# url to repo, displayed in the index page
REPO = "https://github.com/Jv0id/pastebin-worker"

# url to the favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "JP"

# the email displayed in TOS
TOS_MAIL = "jp@8void.sbs"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
